import {StyleSheet} from 'react-native';


const styles = StyleSheet.create({

// CONTAINERS
    splashContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    headerButtonContainer: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'flex-end',
    },
    headerRightContainer: {
        flexDirection: 'row',
        marginBottom: 11,
        width: 120,
        height: 40,
    },
    abbreviationContainer: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FBDABB',
        overflow: 'hidden',
        marginRight: 8,
        marginBottom: 11,
        borderRadius: 20,
    },
    headerIconContainer: {
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent',
        overflow: 'hidden',
        marginRight: 8,
        marginBottom: 11,
        borderRadius: 20,
    },
    pageContainer: {
      flex: 1,
      backgroundColor: '#fff',
    },
    topnavContainer: {
      flex: 1,
      marginHorizontal: 25,
      marginBottom: 8,
    },
    descriptionContainer: {
      flex: 4,
      backgroundColor: '#fff',
    },
    formContainer: {
      flex: 5,
      backgroundColor: '#fff',
      marginHorizontal: 25,
    },
    formHeadContainer: {
      flex: 1,
      backgroundColor: '#fff',
    },
    formInputContainer: {
      flex: 4,
      backgroundColor: '#fff',
    },
    cardTitleContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'flex-start',
      },
    notificationOptionsContainer: {
        height: 32,
        width: '100%',
        flexDirection: 'row',
        alignItems: 'baseline',
        justifyContent: 'flex-start',
    },
    avatarEditContainer: {
        alignItems: 'center',
        marginBottom: 16,
    },
    avatarButtonContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
      },
    profileInputContainer: {
        marginHorizontal: 25,    
    },
    formButtonContainer: {
        flex: 1,
        alignItems: 'center',
    },
    notificationButtonContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        height: 50,
        width: '100%',
      },  

// IMAGES
    splashLogo: {
        width: 300,
        borderRadius: 0,
        alignSelf: 'center',
        marginBottom: 200,
    },
    headerLogo: {
        height: 40,
        width: 146,
        borderRadius: 0,
        marginLeft: 0,
        marginBottom: 11,
        alignSelf: 'flex-start'
    },
    headerButton: {
        height: 40,
        width: 40,
        borderRadius: 0,
        marginLeft: 0,
        marginRight: 30,
        marginBottom: 11,
    },
    logoBackButton: {
        height: 40,
        width: 169,
        borderRadius: 0,
        marginLeft: 0,
        marginRight: 0,
        marginBottom: 11,
    },
    image: {
        width: 120,
        height: 120,
        borderRadius: 0,
        alignSelf: 'center',
        padding: 0,
        marginTop: 35,
        marginBottom: 5,
    },
    blankAvatarContainer: {
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#EDEFEE',
        marginRight: 10,
        marginBottom: 0,
        borderRadius: 40,
      },
    transparentAvatarContainer: {
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor: 'transparent',
        //overflow: 'hidden',
        marginRight: 10,
        marginBottom: 0,
        borderRadius: 40,
    },
      avatarImage: {
    //    resizeMode: 'contain',
      },
    checkboxSize: {
        width: 24,
        height: 24,
        borderRadius: 0,
        alignSelf: 'center',
        padding: 0,
        marginRight: 8,
    },
  

// FONTS
    regularText: {
      fontSize: 16,
      padding: 20,
      marginVertical: 8,
      color: 'black',
      textAlign: 'center',
    },
    regularKarla: {
      fontSize: 22,
      fontFamily: "Karla",
      padding: 20,
      marginVertical: 8,
      color: 'black',
      textAlign: 'center',
    },
    subtitleMarkazi: {
      fontSize: 40,
      fontFamily: "MarkaziText",
      padding: 10,
      marginVertical: 8,
      color: '#48742C',
      textAlign: 'center',
    },
    cardtitleKarla: {
        fontSize: 18,
        fontFamily: "Karla",
        paddingTop: 4,
        paddingBottom: 4,
        marginVertical: 0,
        fontWeight: 'bold',
        color: 'black',
        textAlign: 'left',
    },
    cardcaptionKarla: {
        fontSize: 12,
        fontFamily: "Karla",
        paddingTop: 4,
        paddingBottom: 4,
        marginVertical: 0,
        fontWeight: 'normal',
        color: 'red',
        textAlign: 'left',
    },
    sectionTitleKarla: {
        fontSize: 20,
        fontFamily: "Karla",
        paddingTop: 4,
        paddingBottom: 4,
        marginVertical: 10,
        fontWeight: '900',
        color: 'black',
        textAlign: 'center',
    },
    sectionTitleMarkazi: {
        fontSize: 28,
        fontFamily: "MarkaziText",
        paddingTop: 4,
        paddingBottom: 0,
        marginVertical: 6,
        fontWeight: '900',
        color: 'black',
        textAlign: 'center',
    },
    navigationButtonText: {
        fontSize: 40,
        fontFamily: "MarkaziText",
        textAlign: 'center',
        fontWeight: 'bold',
        color: 'black',
    }, 
    abbreviationKarla: {
        fontSize: 16,
        fontFamily: "Karla",
        paddingTop: 0,
        paddingBottom: 0,
        marginVertical: 0,
        alignSelf: 'center',
        fontWeight: '900',
        color: 'black',
        textAlign: 'center',
    },
    editProfileKarla: {
        fontSize: 12,
        fontFamily: "Karla",
        paddingTop: 0,
        paddingBottom: 0,
        paddingRight: 2,
        marginVertical: 0,
        alignSelf: 'center',
        fontWeight: 'normal',
        color: 'black',
        textAlign: 'right',
    },
    notificationsKarla: {
        fontSize: 16,
        fontFamily: "Karla",
        paddingBottom: 4,
        marginVertical: 0,
        fontWeight: 'normal',
        color: 'black',
        textAlign: 'left',
    },
    undoKarla: {
        fontSize: 16,
        fontFamily: "Karla",
        paddingTop: 0,
        paddingBottom: 0,
        marginVertical: 0,
        alignSelf: 'center',
        fontWeight: '900',
        color: 'white',
        textAlign: 'center',
    },
    logoutKarla: {
        fontSize: 16,
        fontFamily: "Karla",
        paddingTop: 0,
        paddingBottom: 0,
        marginVertical: 0,
        alignSelf: 'center',
        fontWeight: '900',
        color: '#435F57',
        textAlign: 'center',
    },
    
// ELEMENTS
    inputBox: {
      height: 40,
      marginBottom: 12,
      borderWidth: 1,
      padding: 10,
      fontSize: 16,
      borderColor: '#D9D9D9',
      borderRadius: 6,
      backgroundColor: 'white',
    },
    validButton: {
      height: 51,
      width: '100%',
      marginVertical: 16,
      backgroundColor: '#F4CE14',
      borderColor: '#F4CE147',
      borderWidth: 0,
      borderRadius: 10
    }, 
    invalidButton: {
        height: 51,
        width: '100%',
        marginVertical: 16,
        margin: 10,
        backgroundColor: '#EDEFEE',
        borderColor: 'gray',
        borderWidth: 0,
        borderRadius: 10
    }, 
    pressedButton: {
        height: 51,
        paddingHorizontal: 60,
        paddingVertical: 6,
        marginVertical: 16,
        margin: 10,
        backgroundColor: '#BEA00C',
        borderColor: '#F4CE147',
        borderWidth: 0,
        borderRadius: 10
      }, 
    profileAvatarButton: {
        height: 35,
        width: 103,
        marginHorizontal: 6,
        backgroundColor: 'white',
        borderColor: '#8B8B8B',
        borderWidth: 1,
        borderRadius: 8,
        alignContent: 'center',
        justifyContent: 'center',
      }, 
    notiUndoButton: {
        height: 35,
        width: 135,
        marginHorizontal: 6,
        backgroundColor: '#435F57',
        borderColor: '#435F57',
        borderWidth: 1,
        borderRadius: 8,
        alignContent: 'center',
        justifyContent: 'center',
      }, 
    notiLogoutButton: {
        height: 35,
        width: 135,
        marginHorizontal: 6,
        backgroundColor: '#EDEFEE',
        borderColor: '#435F57',
        borderWidth: 1,
        borderRadius: 8,
        alignContent: 'center',
        justifyContent: 'center',
      }, 
    });

  export default styles;
  